# Generated by Django 2.2.1 on 2019-05-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_nomber',
            new_name='phone_number',
        ),
    ]
